"""Example end-to-end z-brains benchmark run (MICs cohort).

This script only holds dataset-specific configuration. The benchmark's
engineering-decision space -- which options are mutually exclusive and which
combine freely -- lives in one authoritative place: ``zbrains_benchmark.py``.
Run ``python zbrains_benchmark.py`` to print that decision space.

Steps performed by :func:`run_benchmark`:
1. Generate a one-factor-at-a-time sweep from the shared baseline.
2. Process (or symlink-reuse) control/patient derivatives per configuration.
3. Validate integrity and compute W-score analyses.
"""

from zbrains.dataset import zbdataset, demographics
from zbrains.environment import zbenv

from zbrains_benchmark import DEFAULT_ENABLED_FAMILIES, run_benchmark

# Feature modalities and blur variants to load for each subject.
FEATURES = ["T1w", "T1w*blur", "FA", "ADC", "thickness", "FLAIR", "FLAIR*blur", "qT1", "qT1*blur"]  # , "fMRI"]

# Root directory prefix used for derivative outputs, intermediate products, and reports.
OUTPUT_DIR_PREFIX = "/host/verges/tank/data/BIDS_MICs/derivatives"

# Paths to preprocessing derivatives generated by external pipelines.
PIPELINE_DIRS = {
    "micapipe_directory": "/data/mica3/BIDS_MICs/derivatives/micapipe_v0.2.0",
    "hippunfold_directory": "/host/verges/tank/data/BIDS_MICs/derivatives/hippunfold_v2.0.0",
    "freesurfer_directory": "/data/mica3/BIDS_MICs/derivatives/freesurfer",
    "raw_data_directory": "/data/mica3/BIDS_MICs/rawdata",
}

# Shared process/validate settings (normalization is added per configuration).
BASE_PIPELINE_SETTINGS = dict(
    features=FEATURES,
    cortical_smoothing=5,
    hippocampal_smoothing=2,
)

# Which OFAT families to sweep. Defaults to every swept family; restrict to run
# only selected families, for example ["normative_model", "control_qc"].
ENABLED_FAMILIES = DEFAULT_ENABLED_FAMILIES

# Flags used to enable or disable modality-specific pipelines.
CORTEX = True
HIPPOCAMPUS = True
SUBCORTICAL = True

# Toggle to force regeneration of patient derivatives in the base directory.
reprocess = False

# Toggle to rebuild the original control cohort in every normalization-specific
# base directory used by this run. Dependent W-score analyses are then rerun.
reprocess_controls = False

# Create the processing environment, including Workbench call settings.
env = zbenv(connectome_workbench_path="/usr/bin", num_threads=32, num_threads_wb=8)

# Load demographics for the control cohort, including columns used in normative modeling.
control_demo = demographics(
    "data/participants_mics_hc_all.csv",
    normative_columns=["AGE", "SEX"],
    normative_dtypes=["int", "binary"],
)

# Assemble the control dataset that serves as normative reference for patient comparisons.
control_dataset = zbdataset(
    "controls",
    demographics=control_demo,
    cortex=CORTEX,
    hippocampus=HIPPOCAMPUS,
    subcortical=SUBCORTICAL,
    **PIPELINE_DIRS,
)

# Load patient demographics and align normative processing with the control cohort.
patient_demo = demographics(
    "data/participants_mics_px_all_test.csv",
    reference=control_demo,
    normative_columns=["AGE", "SEX"],
    normative_dtypes=["int", "binary"],
    # subset=[["sub-PX137", "ses-01"], ["sub-PX138", "ses-01"]], # Example to process a subset of patients
)

# Instantiate the patient dataset using the same modality configuration as the controls.
patient_dataset = zbdataset(
    "patients",
    demographics=patient_demo,
    cortex=CORTEX,
    hippocampus=HIPPOCAMPUS,
    subcortical=SUBCORTICAL,
    **PIPELINE_DIRS,
)

run_benchmark(
    control_dataset=control_dataset,
    patient_dataset=patient_dataset,
    env=env,
    output_dir_prefix=OUTPUT_DIR_PREFIX,
    base_pipeline_settings=BASE_PIPELINE_SETTINGS,
    enabled_families=ENABLED_FAMILIES,
    reprocess=reprocess,
    reprocess_controls=reprocess_controls,
)
