"""Example end-to-end usage of the zbrains pipeline.

This script shows how to:
1. Configure processing directories, feature selections, and smoothing.
2. Instantiate the processing environment with Workbench settings.
3. Build reference (control) and patient datasets with shared pipeline options.
4. Optionally reprocess controls, validate data integrity, and generate analyses.
5. Produce a clinical report comparing patient results to the reference cohort.

Adjust constants below to tailor the workflow to your deployment.
"""

from zbrains.dataset import zbdataset, demographics
from zbrains.environment import zbenv

# Feature modalites and blur variants to load for each subject.
FEATURES = ["FA", "ADC", "thickness", "qT1", "qT1*blur", "FLAIR", "FLAIR*blur"]

# Root directory used for derivative outputs, intermediate products, and reports.
OUTPUT_DIR = "/host/verges/tank/data/ian/zbrains_output"

# Paths to preprocessing derivatives generated by external pipelines.
PIPELINE_DIRS = {
    "micapipe_directory": "/data/mica3/BIDS_MICs/derivatives/micapipe_v0.2.0",
    "hippunfold_directory": "/data/mica3/BIDS_MICs/derivatives/hippunfold_v1.3.0",
    "freesurfer_directory": "/data/mica3/BIDS_MICs/derivatives/freesurfer",
}

# Shared configuration passed to processing, validation, and reporting steps.
PIPELINE_SETTINGS = dict(features=FEATURES, cortical_smoothing=10, hippocampal_smoothing=5)

# Flags used to enable or disable modality-specific pipelines.
CORTEX = True
HIPPOCAMPUS = True
SUBCORTICAL = True

# Toggle to force regeneration of control derivatives when upstream data change.
reprocess = False

# Create the processing environment, including Workbench call settings.
env = zbenv(connectome_workbench_path="/usr/bin", num_threads=20, num_threads_wb=8)

# Load demographics for the control cohort, including columns used in normative modeling.
control_demo = demographics(
    "data/participants_mics_hc_all.csv",
    normative_columns=["AGE", "SEX"],
    normative_dtypes=["int", "binary"],
)

# Assemble the control dataset that serves as normative reference for patient comparisons.
control_dataset = zbdataset(
    "controls",
    demographics=control_demo,
    cortex=CORTEX,
    hippocampus=HIPPOCAMPUS,
    subcortical=SUBCORTICAL,
    **PIPELINE_DIRS,
)

# Optionally recompute all control derivatives if prior outputs are stale or missing.
if reprocess:
    control_dataset.process(output_directory=OUTPUT_DIR, env=env, verbose=True, **PIPELINE_SETTINGS)

# Confirm required files exist and statistics can be derived for the control cohort.
control_dataset.validate(output_directory=OUTPUT_DIR, verbose=False, **PIPELINE_SETTINGS)

# Load patient demographics and align normative processing with the control cohort.
patient_demo = demographics(
    "data/participants_mics_px_all.csv",
    reference=control_demo,
    normative_columns=["AGE", "SEX"],
    normative_dtypes=["int", "binary"],
    subset=[["sub-PX137", "ses-01"], ["sub-PX138", "ses-01"]], # Example to process a subset of patients
)

# Instantiate the patient dataset using the same modality configuration as the controls.
patient_dataset = zbdataset(
    "patients",
    demographics=patient_demo,
    cortex=CORTEX,
    hippocampus=HIPPOCAMPUS,
    subcortical=SUBCORTICAL,
    **PIPELINE_DIRS,
)

# Run subject-level pipelines, then validate inputs before analysis.
patient_dataset.process(output_directory=OUTPUT_DIR, env=env, verbose=True, **PIPELINE_SETTINGS)
patient_dataset.validate(output_directory=OUTPUT_DIR, verbose=False, **PIPELINE_SETTINGS)

# Generate W-score maps comparing each patient to the normative control group.
patient_dataset.analyze(output_directory=OUTPUT_DIR, reference=control_dataset, method="wscore")

# Produce a clinical report summarizing deviations across modalities and structures.
patient_dataset.clinical_report(
    output_directory=OUTPUT_DIR,
    approach="wscore",
    verbose=True,
    env=env,
    features=FEATURES
)

print("done")