#!/bin/bash
#
# MICAPIPE-Z BIDS - Normalization and visualization of structural imaging features
#
version() {
  echo -e "\z-brains April 2023 (Version v.0.0.2 'reborn')\n"
}
export this_version="v0.0.2 'reborn'"
#---------------- FUNCTION: HELP ----------------#
help() {
echo -e "
\033[38;5;141mCOMMAND:\033[0m
   $(basename $0)


\033[38;5;141mARGUMENTS:\033[0m
\t\033[38;5;197m-sub\033[0m             : idBIDS identification
\t\033[38;5;197m-out\033[0m             : Output directory for the processed files <derivatives>.
\t\033[38;5;197m-bids\033[0m            : Path to BIDS directory
\t\033[38;5;120m-ses\033[0m             : OPTIONAL flag that indicates the session name (if omitted will manage as SINGLE session)

   Flags for cortical, hippocampal, and subcortical feature post-processing:
\t\033[38;5;197m-proc_cortex\033[0m         : run post-processing of cortical features for report generation. Relies on micapipe derivatives
\t\t\033[38;5;120m-featureStr\033[0m  : Specify which cortical features should undergo post-processing
\t\t\t         Default is '-featureStr all', meaning all features found under /derivatives/micapipe/subject/maps
\t\t\t         To only process one feature, specify using string: e.g. '-featureStr flair'
\t\t\t         Multiple inputs example = '-featureStr flair,FA,ADC'
\t\t\t         Currently supported features: thickness,flair,FA,ADC,qT1
\t\t\033[38;5;120m-smoothing\033[0m   : Specify size of gaussian smoothing kernel (Default: 5mm). If set to 0, no smoothing is applied.
\t\033[38;5;197m-proc_hippocampus\033[0m    : run post-processing of hippocampal features for report generation. Relies on hippunfold derivatives
\t\t\033[38;5;120m-featureStr\033[0m  : Specify which hippocampal features should undergo post-processing
\t\t\t         Default is '-featureStr all', meaning all available features based on BIDS raw data
\t\t\t         To only process one feature, specify using string: e.g. '-featureStr flair'
\t\t\t         Multiple inputs example = '-featureStr flair,FA,ADC'
\t\t\t         Currently supported features: thickness,flair,FA,ADC,qT1
\t\t\033[38;5;120m-smoothing\033[0m   : Specify size of gaussian smoothing kernel (Default: 2mm). If set to 0, no smoothing is applied.
\t\033[38;5;197m-proc_subcortex\033[0m      : run post-processing of subcortical structures for report generation. Relies on Freesurfer and micapipe
\t\t\033[38;5;120m-featureStr\033[0m  : Specify which subcortical features should undergo post-processing
\t\t\t         Default is '-featureStr all', meaning all available features based on BIDS outputs
\t\t\t         To only process one feature, specify using string: e.g. '-featureStr flair'
\t\t\t         Multiple inputs example = '-featureStr flair,FA,ADC'
\t\t\t         Currently supported features: volume,flair,FA,ADC,qT1

   Flags for case-control analysis and clinical report generation:
\t\033[38;5;197m-regional_z\033[0m          : Multivariate regional analysis
\t\t\033[38;5;120m-thr\033[0m         : Z-score threshold for regional maps
\t\t\t         Default=|1.96|
\t\t\033[38;5;120m-demo\033[0m        : Path to demographic file
\t\t\t         Default=''
\t\t\033[38;5;120m-featureStr\033[0m  : Specify which cortical/subcortical/hippocampal features should be analyzed
\t\t\t         Default=all
\t\t\t         Multiple inputs example = '-featureStr thickness,FA,ADC'
\t\t\033[38;5;120m-smoothCtx\033[0m   : Specify size of gaussian smoothing kernel used to generate cortical input features
\t\t\t         Default=5mm
\t\t\033[38;5;120m-smoothHipp\033[0m  : Specify size of gaussian smoothing kernel used to generate hippocampal input features
\t\t\t         Default=2mm
\t\033[38;5;197m-asymmetry\033[0m           : Multivariate feature asymmetry analysis
\t\t\033[38;5;120m-thr\033[0m         : Z-score threshold for asymmetry maps
\t\t\t         Default=|1.96|
\t\t\033[38;5;120m-demo\033[0m        : Path to demographic file
\t\t\t         Default=''
\t\t\033[38;5;120m-featureStr\033[0m  : Specify which cortical/subcortical/hippocampal features should be analyzed
\t\t\t         Default=all
\t\t\t         Multiple inputs example = '-featureStr thickness,FA,ADC'
\t\t\033[38;5;120m-smoothCtx\033[0m   : Specify size of gaussian smoothing kernel used to generate cortical input features
\t\t\t         Default=5mm
\t\t\033[38;5;120m-smoothHipp\033[0m  : Specify size of gaussian smoothing kernel used to generate hippocampal input features
\t\t\t         Default=2mm


\033[38;5;141mOPTIONS:\033[0m
\t\033[38;5;197m-h|-help\033[0m         : Print help
\t\033[38;5;197m-v|-version\033[0m      : Print software version
\t\033[38;5;197m-force\033[0m           : WARNING this will overwrite the idBIDS directory
\t\033[38;5;197m-quiet\033[0m           : Do not print comments
\t\033[38;5;197m-nocleanup\033[0m       : Do not delete temporary directory at script completion
\t\033[38;5;197m-threads\033[0m         : Number of threads (Default is 6)
\t\033[38;5;197m-tmpDir\033[0m          : Specify location of temporary directory <path> (Default is /tmp)
\t\033[38;5;197m-slim\033[0m            : This option will keep only the main outputs and erase all the intermediate files
\t\033[38;5;197m-mica\033[0m            : Only for MICA local processing
\t\033[38;5;197m-qsub\033[0m            : Only for MICA network processing (SGE mica.q)
\t\033[38;5;197m-qall\033[0m            : Only for MICA network processing (SGE all.q)


\033[38;5;141mUSAGE:\033[0m
    \033[38;5;141m$(basename $0)\033[0m  \033[38;5;197m-sub\033[0m <idBIDS_id> \033[38;5;197m-out\033[0m <outputDirectory> \033[38;5;197m-bids\033[0m <BIDS-directory> \033[38;5;197m-sctx_vol\033[0m


\033[38;5;141mDEPENDENCIES:\033[0m
    > FSL         6.0     (https://fsl.fmrib.ox.ac.uk/fsl/fslwiki)
    > workbench   1.4.2   (https://www.humanconnectome.org/software/workbench-command)
    > python      3.7.6   (https://www.python.org)
    > hippunfold  1.3.0   (https://github.com/khanlab/hippunfold)
    > micapipe    0.2.0   (https://github.com/MICA-MNI/micapipe)


McGill University, MNI, MICA lab, April 2023
https://github.com/MICA-MNI/micapipe
https://github.com/MICA-MNI/z-brains
http://mica-mni.github.io/
"
}

# Source utilities functions from MICAPIPE
if [ -z ${ZBRAINS} ]; then echo "ZBRAINS NOT DEFINED ð¤"; exit 0; fi
if [ -z ${MICAPIPE} ]; then echo "MICAPIPE NOT DEFINED ð¤"; exit 0; fi
source "${MICAPIPE}/functions/utilities.sh"


# -----------------------------------------------------------------------------------------------#
#			ARGUMENTS
# Create VARIABLES
for arg in "$@"
do
  case "$arg" in
  -h|-help)
    help
    exit 1
  ;;
  -v|-version)
    version
    exit 1
  ;;
  -sub)
    id=$2
    shift;shift
  ;;
  -out)
    out=$2
    shift;shift
  ;;
  -bids)
    BIDS=$2
    shift;shift
  ;;
  -ses)
    SES=$2
    shift;shift
  ;;
  -proc_cortex)
    ctxPROC=TRUE
    shift
  ;;
  -featureStr)
    feat=$2
    shift;shift
  ;;
  -smoothing)
    smooth=$2
    shift;shift
  ;;
  -proc_hippocampus)
    hippoPROC=TRUE
    shift
  ;;
  -featureStr)
    feat=$2
    shift;shift
  ;;
  -smoothing)
    smooth=$2
    shift;shift
  ;;
  -proc_subcortex)
    sctxPROC=TRUE
    shift
  ;;
  -featureStr)
    feat=$2
    shift;shift
  ;;
  -regional_z)
    REGZ=TRUE
    shift
  ;;
  -thr)
    thr=$2
    shift;shift
  ;;
  -demo)
    demo=$2
    shift;shift
  ;;
  -smoothCtx)
    smoothCTX=$2
    shift;shift
  ;;
  -smoothHipp)
    smoothHIPP=$2
    shift;shift
  ;;
  -asymmetry)
    ASYMMETRY=TRUE
    shift
  ;;
  -thr)
    thr=$2
    shift;shift
  ;;
  -demo)
    demo=$2
    shift;shift
  ;;
  -featureStr)
    feat=$2
    shift;shift
  ;;
  -smoothCtx)
    smoothCTX=$2
    shift;shift
  ;;
  -smoothHipp)
    smoothHIPP=$2
    shift;shift
  ;;
  -mica)
    mica=TRUE
    shift
  ;;
  -tmpDir)
    tmpDir=$2
    shift;shift;
  ;;
  -qsub)
    micaq=TRUE
    shift
  ;;
  -qall)
    qall=TRUE
    shift
  ;;
  -nocleanup)
    nocleanup=TRUE
    shift
  ;;
  -threads)
    threads=$2
    shift;shift
  ;;
  -force)
    force=TRUE
    shift
  ;;
  -quiet)
    quiet=TRUE
    shift
  ;;
  -*)
    Error "Unknown option ${2}"
    help
    exit 1
  ;;
    esac
done

# argument check out & WARNINGS
arg=($id $out $BIDS)
if [ ${#arg[@]} -lt 3 ]; then
Error "One or more mandatory arguments are missing:
               -sub  : $id
               -out  : $out
               -bids : $BIDS"
help; exit 1; fi
runs=($ALL $ctxPROC $hippoPROC $sctxPROC $REGZ $ASYMMETRY)
if [ "${#runs[@]}" -lt 1 ]; then
Error "A processing flag is missing:
                    -proc_cortex
                    -proc_hippocampus
                    -proc_subcortex
                    -regional_z
                    -asymmetry"
help; exit 1; fi

# Get the real path of the Inputs
outDeriv=$(realpath $out)
outz=$(realpath $out)/z-brains
outm=$(realpath $out)/micapipe_v0.2.0
BIDS=$(realpath $BIDS)
id=${id/sub-/}
here=$(pwd)

# Number of session (Default is "ses-pre")
if [ -z ${SES} ]; then SES="SINGLE"; else SES="ses-${SES/ses-/}"; fi

# Assigns variables names
bids_variables "$BIDS" "$id" "$outm" "$SES"

# Check BIDS Directory
if [ ! -d "${subject_bids}" ]; then Error "$id was not found on the BIDS directory\n\t Check ls ${subject_bids}"; exit 1; fi

# Erase temporary files by default
if [ -z ${nocleanup} ]; then nocleanup=FALSE; fi

# No print Do_cmd
if [ "$quiet" = "TRUE" ]; then export quiet=TRUE; fi

# Temporary directory
if [ -z ${tmpDir} ]; then export tmpDir=/tmp; else tmpDir=$(realpath $tmpDir); fi

# Setting Surface Directory
Nrecon=($(ls "${dir_QC}/${idBIDS}_module-proc_surf-"*.json 2>/dev/null | wc -l))
if [[ "$Nrecon" -lt 1 ]]; then
  Error "Subject $id doesn't have a module-proc_surf: run -proc_surf"; exit 1
elif [[ "$Nrecon" -eq 1 ]]; then
  module_qc=$(ls "${dir_QC}/${idBIDS}_module-proc_surf-"*.json 2>/dev/null)
  recon="$(echo ${module_qc/.json/} | awk -F 'proc_surf-' '{print $2}')"
elif [[ "$Nrecon" -gt 1 ]]; then
  Warning "${idBIDS} has been processed with freesurfer and fastsurfer."
  if [[ "$FastSurfer" == "TRUE" ]]; then
    Note "fastsurfer will run: $FastSurfer\n"; recon="fastsurfer";
  else
    Note "freesurfer is the default"; recon="freesurfer"
  fi
fi
# Set surface directory
set_surface_directory "${recon}"
if [ -z ${dir_subjsurf} ]; then FSdir="FALSE"; else  FSdir=$(realpath $dir_subjsurf); fi


# -----------------------------------------------------------------------------------------------#
# Set optional arguments

# Feature selection and smoothing
if [ -z ${feat} ]; then featStr=DEFAULT; else featStr="$feat"; fi
if [ -z ${smooth} ]; then smoothing=DEFAULT; else smoothing="$smooth"; fi
if [ -z ${smoothCTX} ]; then smoothingCTX=DEFAULT; else smoothingCTX="$smoothCTX"; fi
if [ -z ${smoothHIPP} ]; then smoothingHIPP=DEFAULT; else smoothingHIPP="$smoothHIPP"; fi

# arguments for regional and asymmetry analysis
if [ -z "$thr" ]; then thr=1.96; fi
if [ -z "$demo" ]; then demo=''; fi

# -----------------------------------------------------------------------------------------------#
Title "z-brains pipeline - (Version $this_version) \n\t\tidBIDS: $id Session: $SES"

# -----------------------------------------------------------------------------------------------#
# Launch the init file for local processing at MICA lab
if [ "$micaq" = "TRUE" ] || [ "$qall" = "TRUE" ] || [ "$mica" = "TRUE" ]; then
    source "${MICAPIPE}/functions/init.sh"
else

    # -----------------------------------------------------------------------------------------------#
    #   CHECK PACKAGES DEPENDENCIES
    # tree display
    if [[ -z $(which tree) ]]; then Warn "tree function was not found"; fi
    # freesurfer
    if [[ -z $(which recon-all) ]]; then Error "FreeSurfer was not found"; exit 1; fi
    # FSL
    if [[ -z $(which flirt) ]]; then Error "FSL was not found"; exit 1; fi
    # ANTSx
    if [[ -z $(which antsRegistration) ]]; then Error "ANTs was not found"; exit 1; fi
    # workbench
    if [[ -z $(which wb_command) ]]; then Error "WorkBench was not found"; exit 1; fi
fi

# Processing
if [[ -z $PROC ]]; then export PROC="LOCAL"; fi

# Number of THREADS used by ANTs and workbench, default is 6 if not defined by -threads
if [[ -z $threads ]]; then export threads=6; fi
Info "z-brains will use $threads threads for multicore processing"

# Directories check
if [[ ${force} == TRUE ]]; then
  Warning "$id processing directory will be overwritten"
  rm -rf $outz/${idBIDS};
fi

# -----------------------------------------------------------------------------------------------#
# Timer & Beginning
aloita=$(date +%s)

# Create tmp dir
if [ ! -d ${tmpDir} ]; then Do_cmd mkdir -p $tmpDir; fi

# Create output directories
if [ ! -d ${outz} ]; then Do_cmd mkdir -p ${outz}; fi

# Handle Single Session
if [ "$SES" == "SINGLE" ]; then
  export subject_dirz=$outz/${subject}
  ses=""
else
  export subject_dirz=$outz/${subject}/${SES}
  ses="_${SES}"
fi

# subject_dir
# Creates subject directory if it doesn't exist
if [ ! -d "${subject_dirz}" ]; then
    Info "Subject ${idBIDS} directory doesn't exist, creating..."
    Do_cmd mkdir -m 770 -p "${subject_dirz}"/{logs,maps,norm-z,norm-propensity,norm-normative}
    Do_cmd mkdir -m 770 -p "${subject_dirz}"/maps/{subcortex,cortex,hippocampus}
    Do_cmd mkdir -m 770 -p "${subject_dirz}"/norm-z/{subcortex,cortex,hippocampus}
    Do_cmd mkdir -m 770 -p "${subject_dirz}"/norm-propensity/{subcortex,cortex,hippocampus}
    Do_cmd mkdir -m 770 -p "${subject_dirz}"/norm-normative/{subcortex,cortex,hippocampus}
    chmod g+xX -R "${subject_dirz}"
fi

# -----------------------------------------------------------------------------------------------#
# subject_dir
if [ ! -d "${subject_dir}" ]; then
    Error "Subject ${id} directory doesn't exist, run micapipe v0.2.0 before running z-brains"
exit 1; fi

# freesurfer Directory
if [ ! -d "$FSdir" ]; then
    Error "Subject ${id} freesurfer directory doesn't exist, run micapipe v0.2.0 before running z-brains"
exit 1; fi

# Log directory
outLogs="${subject_dirz}/logs/"

# Pipeline description json
micapipe_json


# -----------------------------------------------------------------------------------------------#
# # #        Structural processing: Cortex
# -----------------------------------------------------------------------------------------------#
if [ "$ALL" = "TRUE" ] || [ "$ctxPROC" = "TRUE" ]; then
    log_file_str=$outLogs/ctx_proc_$(date +'%d-%m-%Y')

    # Define UTILITIES directory
    export scriptDir=${ZBRAINS}/functions

    COMMAND="${scriptDir}/01_ctx_proc.sh $BIDS $id $out $SES $FSdir $nocleanup $threads $tmpDir $featStr $smoothing"
    # mica.q - Structural processing: Cortex
    if [[ $micaq == "TRUE" ]]; then
        Info "MICA qsub - Structural processing: Cortex"
        Warning "This option only works on the MICA workstations"
        export PROC="qsub-MICA"
        # Info "Setting a warper to run on mica.q"
        qsub -q mica.q -pe smp $threads -l h_vmem=6G -N q${id}_ctx_proc -e ${log_file_str}.e -o ${log_file_str}.txt $COMMAND $PROC
             # all.q - Structural processing: Cortex
    elif [[ $qall == "TRUE" ]]; then
        Info "all.q qsub - Structural processing: Cortex"
        Warning "This option only works on the McGill BIC network"
        export PROC="qsub-all.q"
        # Info "Setting a warper to run on all.q"
        qsub -q all.q -pe all.pe $threads -l h_vmem=6G -N q${id}_ctx_proc -e ${log_file_str}.e -o ${log_file_str}.txt $COMMAND $PROC
    else
        #  LOCAL - Structural processing: Cortex
        $COMMAND $PROC 2>&1 | tee -a ${log_file_str}.txt
    fi
fi


# -----------------------------------------------------------------------------------------------#
# # #        Structural processing: Hippocampus
# -----------------------------------------------------------------------------------------------#
if [ "$ALL" = "TRUE" ] || [ "$hippoPROC" = "TRUE" ]; then
    log_file_str=$outLogs/hippo_proc_$(date +'%d-%m-%Y')

    # Define UTILITIES directory
    export scriptDir=${ZBRAINS}/functions

    COMMAND="${scriptDir}/01_hippo_proc.sh $BIDS $id $out $SES $FSdir $nocleanup $threads $tmpDir $featStr $smoothing"
    # mica.q - Structural processing: Hippocampus
    if [[ $micaq == "TRUE" ]]; then
        Info "MICA qsub - Structural processing: Hippocampus"
        Warning "This option only works on the MICA workstations"
        export PROC="qsub-MICA"
        # Info "Setting a warper to run on mica.q"
        qsub -q mica.q -pe smp $threads -l h_vmem=6G -N q${id}_hippo_proc -e ${log_file_str}.e -o ${log_file_str}.txt $COMMAND $PROC
             # all.q - Structural processing: Hippocampus
    elif [[ $qall == "TRUE" ]]; then
        Info "all.q qsub - Structural processing: Hippocampus"
        Warning "This option only works on the McGill BIC network"
        export PROC="qsub-all.q"
        # Info "Setting a warper to run on all.q"
        qsub -q all.q -pe all.pe $threads -l h_vmem=6G -N q${id}_hippo_proc -e ${log_file_str}.e -o ${log_file_str}.txt $COMMAND $PROC
    else
        #  LOCAL - Structural processing: Hippocampus
        $COMMAND $PROC 2>&1 | tee -a ${log_file_str}.txt
    fi
fi


# -----------------------------------------------------------------------------------------------#
# # #        Structural processing: Subcortex
# -----------------------------------------------------------------------------------------------#
if [ "$ALL" = "TRUE" ] || [ "$sctxPROC" = "TRUE" ]; then
    log_file_str=$outLogs/sctx_proc_$(date +'%d-%m-%Y')

    # Define UTILITIES directory
    export scriptDir=${ZBRAINS}/functions

    COMMAND="${scriptDir}/01_sctx_proc.sh $BIDS $id $outDeriv $SES $FSdir $nocleanup $threads $tmpDir $featStr"
    # mica.q - Structural processing: Subcortex
    if [[ $micaq == "TRUE" ]]; then
        Info "MICA qsub - Structural processing: Subcortex"
        Warning "This option only works on the MICA workstations"
        export PROC="qsub-MICA"
        # Info "Setting a warper to run on mica.q"
        qsub -q mica.q -pe smp $threads -l h_vmem=6G -N q${id}_sctx_proc -e ${log_file_str}.e -o ${log_file_str}.txt $COMMAND $PROC
             # all.q - Structural processing: Subcortex
    elif [[ $qall == "TRUE" ]]; then
        Info "all.q qsub - Structural processing: Subcortex"
        Warning "This option only works on the McGill BIC network"
        export PROC="qsub-all.q"
        # Info "Setting a warper to run on all.q"
        qsub -q all.q -pe all.pe $threads -l h_vmem=6G -N q${id}_sctx_proc -e ${log_file_str}.e -o ${log_file_str}.txt $COMMAND $PROC
    else
        #  LOCAL - Structural processing: Subcortex
        $COMMAND $PROC 2>&1 | tee -a ${log_file_str}.txt
    fi
fi


# -----------------------------------------------------------------------------------------------#
# # #        Multivariate analysis: REGIONAL Z
# -----------------------------------------------------------------------------------------------#
if [ "$ALL" = "TRUE" ] || [ "$REGZ" = "TRUE" ]; then
    log_file_str=$outLogs/regional_z_$(date +'%d-%m-%Y')

    export scriptDir=${ZBRAINS}/functions

    COMMAND="${scriptDir}/02_regional_analysis.sh $BIDS $id $out $SES $nocleanup $threads $tmpDir $thr $demo"
    # mica.q - Multivariate analysis: REGIONAL Z
    if [[ $micaq == "TRUE" ]]; then
        Info "MICA qsub - Multivariate analysis: REGIONAL Z"
        Warning "This option only works on the MICA workstations"
        export PROC="qsub-MICA"
        # Info "Setting a warper to run on mica.q"
        qsub -q mica.q -pe smp $threads -l h_vmem=6G -N q${id}_regionZ -e ${log_file_str}.e -o ${log_file_str}.txt $COMMAND $PROC
             # all.q - Multivariate analysis: REGIONAL Z
    elif [[ $qall == "TRUE" ]]; then
        Info "all.q qsub - Multivariate analysis: REGIONAL Z"
        Warning "This option only works on the McGill BIC network"
        export PROC="qsub-all.q"
        # Info "Setting a warper to run on all.q"
        qsub -q all.q -pe all.pe $threads -l h_vmem=6G -N q${id}_regionZ -e ${log_file_str}.e -o ${log_file_str}.txt $COMMAND $PROC
    else
        #  LOCAL - Multivariate analysis: REGIONAL Z
        $COMMAND $PROC 2>&1 | tee -a ${log_file_str}.txt
    fi
fi

# -----------------------------------------------------------------------------------------------#
# # #        Multivariate analysis: ASYMMETRY
# -----------------------------------------------------------------------------------------------#
if [ "$ALL" = "TRUE" ] || [ "$ASYMMETRY" = "TRUE" ]; then
    log_file_str=$outLogs/asymmetry_$(date +'%d-%m-%Y')

    export scriptDir=${ZBRAINS}/functions

    COMMAND="${scriptDir}/02_asymmetry.sh $BIDS $id $out $SES $nocleanup $threads $tmpDir $thr $demo $featStr $smoothingCTX $smoothingHIPP"
    # mica.q - Multivariate analysis: ASYMMETRY
    if [[ $micaq == "TRUE" ]]; then
        Info "MICA qsub - Multivariate analysis: ASYMMETRY"
        Warning "This option only works on the MICA workstations"
        export PROC="qsub-MICA"
        # Info "Setting a warper to run on mica.q"
        qsub -q mica.q -pe smp $threads -l h_vmem=6G -N q${id}_asymmetry -e ${log_file_str}.e -o ${log_file_str}.txt $COMMAND $PROC
             # all.q - Multivariate analysis: ASYMMETRY
    elif [[ $qall == "TRUE" ]]; then
        Info "all.q qsub - Multivariate analysis: ASYMMETRY"
        Warning "This option only works on the McGill BIC network"
        export PROC="qsub-all.q"
        # Info "Setting a warper to run on all.q"
        qsub -q all.q -pe all.pe $threads -l h_vmem=6G -N q${id}_asymmetry -e ${log_file_str}.e -o ${log_file_str}.txt $COMMAND $PROC
    else
        #  LOCAL - Multivariate analysis: ASYMMETRY
        $COMMAND $PROC 2>&1 | tee -a ${log_file_str}.txt
    fi
fi

: <<'END'
END


# -----------------------------------------------------------------------------------------------#
#			 Total Running Time
lopuu=$(date +%s)
eri=$(echo "$lopuu - $aloita" | bc)
eri=$(echo print $eri/60 | perl)

# Cleanup if processing was local
if [ $PROC == "LOCAL" ] || [ "$mica" = "TRUE" ]; then
    cleanup "$tmpDir/*_micapipe*_${id}" "$nocleanup" "$here"
fi
Title "GLOBAL z-brains running time with $PROC processing:\033[38;5;220m $(printf "%0.3f\n" ${eri}) minutes \033[38;5;141m"
