#!/bin/bash
# Change the current working directory to the parent directory
cd "$(dirname "$0")"
pyinit_flag=0

# Set a default value for env_path
default_env_path="/data/mica1/01_programs/miniforge3"
env_path=$default_env_path

for arg in "$@"
do
    if [[ $arg == --pyinit=* ]]; then
        env_path="${arg#*=}"
        pyinit_flag=1
    fi
done

if [[ $env_path != "false" ]]; then
    source $env_path/bin/activate
    conda activate zbrains
    if [[ $pyinit_flag -eq 0 ]]; then
        echo "The --pyinit argument was left empty, zbrains will use the MICA lab default Python environment, to disable this behaviour and use your current environment use the --pyinit=false argument."
    fi
else
    echo "The --pyinit argument was set to false, zbrains will use your currently active Python environment."
fi
python -m src.zbrains "$@"