#!/bin/bash
# Change the current working directory to the parent directory
cd "$(dirname "$0")"
pyinit_flag=0

# Set a default value for env_path
default_env_path="/data/mica1/01_programs/miniforge3"
env_path=$default_env_path

# Create an array to hold the arguments for src.zbrains
args=()

for arg in "$@"
do
    if [[ $arg == --pyinit=* ]]; then
        env_path="${arg#*=}"
        pyinit_flag=1
    else
        # If the argument is not --pyinit, add it to the args array
        args+=("$arg")
    fi
done

if [[ $env_path != "false" ]]; then
    echo "Activating Python environment at $env_path"
    source $env_path/bin/conda
    echo "Activated zbrains environment"
    conda activate zbrains
    
    if [[ $pyinit_flag -eq 0 ]]; then
        echo "The --pyinit argument was left empty, zbrains will use the MICA lab default Python environment, to disable this behaviour and use your current environment use the --pyinit=false argument."
    fi
else
    echo "The --pyinit argument was set to false, zbrains will use your currently active Python environment."
fi

# Pass the args array to src.zbrains
python -m src.zbrains "${args[@]}"