#list of analysis levels in the bids app
analysis_levels:
 - participant


# mapping from analysis_level to set of target rules or files
targets_by_analysis_level:
  participant:
    - 'all'  # if '', then the first rule is run

# Versioning for each pipeline
versions:
  hippunfold: 1.3.0
  micapipe: 0.2.0
  freesurfer: None


# configuration for the command-line parameters to make available
# passed on the argparse add_argument()
parse_args:
  --input-directory:
    help: "Path to input BIDS directory. Micapipe, Freesurfer, and HippUnfold should be found in the derivatives of this."
    required: true
  --reference-demographics-csv:
    help: "Path to reference demographics CSV"
    required: true
  --patient-demographics-csv:
    help: "Path to patient demographics CSV"
    required: true
  --scoring_methods:
    help: "Scoring method for analysis (zscore or wscore)"
    choices: ["z", "w"]
    default: "zscore"

structures:
  - cortex
  - hippocampus
  - subcortex

scoring_methods:
  - z

smoothings:
  cortex:
    - 5
  hippocampus:
    - 2
  subcortex:
    - NA

sfwm_depths:
  - 1.0
  - 2.0

features:
  - qT1
  - FA
  - ADC
  - thickness
features_to_blur:

hemis:
  cortex:
    - L
    - R
  hippocampus:
    - L
    - R
  subcortex:
    - NA

resolution:
  cortex: 32k
  hippocampus: 0p5mm
  subcortex: NA

report_params:
  analyses: ["regional", "asymmetry"]
  threshold: 1.96
  threshold_alpha: 0.3
  label_ctx: midthickness
  label_hip: midthickness
  color_bar: bottom
  cmap: cmo.balance
input_path: /data/mica3/BIDS_MICs
pybids_inputs: {}