#list of analysis levels in the bids app
analysis_levels:
 - participant


# mapping from analysis_level to set of target rules or files
targets_by_analysis_level:
  participant:
    - 'all'  # if '', then the first rule is run

# Versioning for each pipeline
versions:
  hippunfold: 1.3.0
  micapipe: 0.2.0
  freesurfer: None


demographics_csv: /path/to/demographics.csv
workbench_path: /path/to/workbench

# configuration for the command-line parameters to make available
# passed on the argparse add_argument()
parse_args:
  - ["--input-directory", {"help": "Path to input BIDS directory. Micapipe, Freesurfer, and HippUnfold should be found in the derivatives of this.", "required": True}]
  - ["--demographics-csv", {"help": "Path to demographics CSV", "required": True}]
  - ["--scoring-method", {"help": "Scoring method for analysis (zscore or wscore)", "choices": ["zscore", "wscore"], "default": "zscore"}]

# Docker and singularity containers may be defined here
containers:
    # fsl: 'docker://brainlife/fsl/6.0.0'

# List of superficial white matter depths (in mm) for blurring
sfwm_depths:
  - 1.0
  - 2.0

# Features, hemispheres, smoothing levels, and scoring methods for workflow
features:
  - qT1
  - FA
  - ADC
  - FLAIR
  - thickness
hemis:
  - L
  - R
smoothings:
  cortex:
    - 5
  hippocampus:
    - 2

# Add resolution parameters for cortex and hippocampus
resolution:
  cortex: 32k
  hippocampus: 0p5mm
